name: Action Example
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name:'     
        required: true
        default: 'Alice'

jobs:
  unittest:
    strategy:
      matrix:
        servers: [ubuntu-latest]
    runs-on: ${{matrix.servers}}
    steps:
      - name: Checkout Repo
        run: |
          rm -rf ${{github.event.repository.name}}
          git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}
          git -C "${{github.workspace}}/${{github.event.repository.name}}" checkout ${{github.ref}}
      - name: Do Something
        run: |
          cd ${{github.event.repository.name}}
          echo Something
      - name: Do greeting on master branch
        if: ${{github.ref_name == 'master' || github.ref_name == 'main'}}
        run: |
          echo Hello, ${{github.event.inputs.name}}
      - name: Cleanup
        run: |
          rm -rf ${{github.event.repository.name}}
